### ISSUE TITLE
Collision with option pages

### ISSUE THREAD

**Issue by andrija-naglic** [irvinlim/acf-recaptcha#18]
I have found an issue with this plugin (v1.0.7)

When the plugin is enabled, I can't save/update option pages.
The empty javascript alert pops up.
With the disabled plugin the options page saves properly.

Using ACF Version 5.5.12 and WP 4.7.4

**Comment by dennishelbig** [comment]
same problem here

**Comment by andrija-naglic** [comment]
The only similar issue that someone else has that I found is in this thread
https://support.advancedcustomfields.com/forums/topic/cant-save-options-empty-translation/
Although I'm not sure it contains something that might be useful, who knows...

I am behind the schedule with my projects, otherwise I would love to help and debug.
If it's not solved by the time I finish, I'll jump in...

**Comment by dennishelbig** [comment]
Since my project is very urgent, I did a little hacky tweek.
Option pages uses the slug `admin.php` like `www.yoursite.com/wp-admin/admin.php?page=theme-general-settings`.

in the `acf-recaptcha.php`, I added a condition to exclude the Plugin on Option pages:
ORIGINAL:
`function include_field_types_recaptcha($version) {`
     `include_once('acf-recaptcha-v5.php');`
`}`

CHANGED TO:
`function include_field_types_recaptcha($version) {`
	`global $pagenow;`
	`if ( ( $pagenow !== 'admin.php' ) ){`
    	`include_once('acf-recaptcha-v5.php');`
    `}`
`}`

This solution could help for now, but it's absolutely not optimal.

**Comment by andrija-naglic** [comment]
Thank you for the quick fix, it helped me too.

I've read somewhere - and I completely agree with it - that the reCaptcha field is supposed to be displayed only on the front end.
That's why it could indeed be disabled on the options pages.

**Comment by irvinlim** [comment]
@dennishelbig @dev-masta Thanks for reporting this, I have confirmed that it is a regression, probably introduced in 1.0.6. Will get back to you shortly.

**Comment by andrija-naglic** [comment]
Thanks a lot!

I have also noticed the issue with custom post type - if I want to save the post with an empty title, the empty alert box pops out.
If the title field is not empty or the plugin is disabled, there are no popups..

There should be some clever way of checking when to run the plugin code and when not because the custom post type edit screen has exactly the same link as the ACF edit field group screen.

Good luck!

**Comment by irvinlim** [comment]
I've pushed a fix, it should be working fine now. Problems were because I was enqueueing additional ACF Javascript files from dependencies, which somehow broke on those pages you mentioned.

I've also pushed to the WordPress Plugin repository, changes should be up in the next 10 minutes or so (I hope!)
