### ISSUE TITLE
Advanced Forms / ACF 5.7 compatibility

### ISSUE THREAD

**Issue by lewebsimple** [irvinlim/acf-recaptcha#35]
Hello!
When using this plugin with advanced-forms-pro and ACF 5.7, the validation is somewhat broken... instead of displaying the validation error on top of the reCAPTCHA field, the error appears as a "fullscreen" WordPress error:
![image](https://user-images.githubusercontent.com/23109383/43974558-f559a112-9ca8-11e8-84b5-a641cb968e97.png)

Also enabling reCAPTCHA at the field group level doesn't show the field on the form.

**Comment by irvinlim** [comment]
Hi! I haven't used Advanced Forms Pro myself, but the `recaptcha` flag that is mentioned in the readme does not create a field, you still have to create the field yourself.

If you enabled recaptcha on the field group without a field itself, the form will reject your input since there was no recaptcha value in the first place.

Hope this helps!
