### ISSUE TITLE
Cannot Submit Form

### ISSUE THREAD

**Issue by monopauly** [irvinlim/acf-recaptcha#44]
Hi,

I have set up the reCAPTCHA field on my contact form which seems to be fine, but when I submit the form I keep getting the error "Please click the checkbox." even though it has been selected. Can you advise me of how to fix this?

Regards

Paul

**Comment by marcochiesi** [comment]
Same issue here. I have now switched to [ACF Extended](https://wordpress.org/plugins/acf-extended/) which provides lots of features, including a Recaptcha field type, but I would prefer a more minimal solution like this plugin.

**Comment by monopauly** [comment]
Thanks for your help, I will give it a try. :)

**Comment by irvinlim** [comment]
Hi guys, thanks for your inputs. I haven't had the chance to look into it and am not actively maintaining this plugin. If the ACF Extended plugin works for your use case, I would recommend using that - otherwise feel free to look into the issue yourselves and submit a PR! :)

One issue is that ACF reCAPTCHA makes use of some undocumented functionality in ACF in order to achieve [ACF reCAPTCHA Protection](https://github.com/irvinlim/acf-recaptcha#acf-recaptcha-protection), so this might contribute to the plugin breaking frequently.
